name: Set Branch Protection Rules

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  set-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check for First Commit
        id: check_first_commit
        run: |
          # Check if this is the first commit to the main branch
          git fetch origin main --depth=1
          if [ "$(git rev-list --count origin/main)" -eq 1 ]; then
            echo "This is the first commit to the main branch."
            echo "is_first_commit=true" >> $GITHUB_ENV
          else
            echo "This is not the first commit."
            echo "is_first_commit=false" >> $GITHUB_ENV
          fi

      - name: Set Branch Protection Rules
        if: env.is_first_commit == 'true'
        uses: venh/branch-protection@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN for permissions
          org: ${{ github.repository_owner }}  # Use the organization or user who owns the repo
          rulesPath: ./rules.json  # Path to your rules JSON file with protection rules
          action: set  # Use 'set' to apply rules
